# Generated by Django 2.2 on 2019-04-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='author',
            new_name='user',
        ),
    ]
