# Generated by Django 2.2 on 2019-04-28 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190428_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='skill_c',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='votes',
            name='skill_d',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='votes',
            name='skill_e',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='votes',
            name='skill_a',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='votes',
            name='skill_b',
            field=models.IntegerField(default=5),
        ),
    ]
