# Generated by Django 2.2 on 2019-04-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_roster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='player',
            new_name='players',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='active',
        ),
    ]
