# Generated by Django 2.2 on 2019-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190512_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='players',
            field=models.CharField(max_length=1000),
        ),
    ]
